project:
  type: website
  output-dir: docs

website:
  title: "Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/happy956
format:
  html:
    theme: lux
    toc: true
    css: styles.css